
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Available_Packages

on:
  schedule:
    # once a week (every Monday at 3AM)
    - cron: "0 3 * * 1"

jobs:
  Checks:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/yast/head/containers/yast-ruby:latest
      options: --privileged

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Check Available Apache Packages
      run: ./ci_package_check.sh
